# General Settings

title: Charles C. Lee
email: charleschanlee@gmail.com

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'http://chanchar.github.io/' # the base hostname & protocol for your site

# Build settings
markdown:            kramdown
relative_permalinks: false
permalink:           /:year/:month/:day/:title.html

pagination:          true
paginate:            8

sass:
    sass_dir: _sass
    style:    compressed

defaults:
  -
      scope:
        path: "_posts"
        type: "posts"
      values:
        reading_time: true
        show_tags: true
        show_categories: true